// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyLU54_D88Z4XkqKZHxBeYTmompaqAGb8',
    appId: '1:694955298196:android:1854e95c8aa4bdec271381',
    messagingSenderId: '694955298196',
    projectId: 'riskmanage-80b08',
    storageBucket: 'riskmanage-80b08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwAqjcPQL3SDqR0TNeVeN_r5yRw5lx0Eg',
    appId: '1:694955298196:ios:9c7b790b310abb6b271381',
    messagingSenderId: '694955298196',
    projectId: 'riskmanage-80b08',
    storageBucket: 'riskmanage-80b08.firebasestorage.app',
    androidClientId: '694955298196-5op5337is6d0vb6veaj00qvkcap4p4qd.apps.googleusercontent.com',
    iosClientId: '694955298196-tp0d4jlbslf6uamqp4u14p776d7qat9j.apps.googleusercontent.com',
    iosBundleId: 'com.diary.app',
  );

}